name: End-to-End Tests with Playwright

on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.52.0-noble
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm ci
    - run: npm run build
      env:
        BASE_PATH: '/${{ github.event.repository.name }}'
    - run: npx playwright test
    - if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: e2e-report/
        retention-days: 30
    - if: ${{ inputs.upload-pages-artifact }}
      uses: actions/upload-artifact@v4
      with:
        path: build/